### ISSUE TITLE
Game crash (no autorestore possible)

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#458] opened 2023-09-05 07:22 UTC
This happened when I tried to descend the stairs on level 2 of the dungeons:
[9] /hackem-1.2.0/hackem(savestateinlock+0x2f4) [0x559fd5a47b71]
[10] /hackem-1.2.0/hackem(save_currentstate+0x61) [0x559fd577e2ec]
[11] /hackem-1.2.0/hackem(goto_level+0x1c6e) [0x559fd57801b2]
[12] /hackem-1.2.0/hackem(next_level+0xa1) [0x559fd57ce51a]
[13] /hackem-1.2.0/hackem(dodown+0x1039) [0x559fd577de63]

After failed autorestore:
malloc(): invalid size (unsorted)

There was nothing remarkable going on, I had just finished a session at my stash of mixing potions, enchanting armor and cloning a wand of death.

**Comment by elunna** [comment] 2023-09-05 07:24
Can you get a link to the ttyrec leading up to it please?

**Comment by k21971** [comment] 2023-09-05 11:20
Backtrace - https://termbin.com/76gq

**Comment by mobi-leuser** [comment] 2023-09-05 12:54
crashed again after cloning a wand of death and going down the stairs.

**Comment by mobi-leuser** [comment] 2023-09-05 13:06
oh, maybe important: I put the cloned wand in my chest and then went downstairs

**Comment by elunna** [comment] 2023-09-13 11:45
Tried reproducing but no luck. I went back to the master branch, tried cloning different wands of death (uncharged and charged), used uncursed and blessed scrolls of cloning. Tried bringing the clones with me downstairs, tried storing them in bags/boxes.

**Comment by mobi-leuser** [comment] 2023-09-13 12:17
Unfortunately I don't remember if the wand happened to be gold...

**Comment by elunna** [comment] 2023-09-13 12:20
That's an interesting point - I didn't think of that. I was assuming it was related to gold coins...

**Comment by elunna** [comment] 2023-10-05 14:40
Since we can't reproduce this - going to close for now. Might also be fixed with wand cloning updates and this commit that fixes tourist shop id 35c2e9325

**Closed by elunna** 2023-10-05 14:40 UTC
