### ISSUE TITLE
Disrupter as alternate weapon: detects undead after save/reload

### ISSUE THREAD

**Issue by mobi-leuser** [elunna/hackem#445] opened 2023-08-18 14:29 UTC

**Comment by mobi-leuser** [comment] 2023-08-18 14:31
When I have Disrupter as alternate weapon (not wielded) and I save and reload, I get the undead detection that should only happen when the weapon is wielded.

**Comment by elunna** [comment] 2023-08-20 18:58
I tried to reproduce it this weekend but didn't have any luck. What role/race were you?

**Comment by mobi-leuser** [comment] 2023-08-20 19:02
priest/orc. Weird, I can consistently reproduce it in my game.

**Comment by mobi-leuser** [comment] 2023-08-20 19:08
I'm also using Mjollnir and use "x" to switch.

**Comment by mobi-leuser** [comment] 2023-08-20 19:19
Just did this again in the valley of the dead. Wielding Disrupter shows undead as expected. Press x, wielding Mjollnir. Undead disappear from view. Save. Reload. All the undead are visible despite wielding Mjollnir.

**Comment by elunna** [comment] 2023-09-13 09:58
Was this in curses or TTY?

**Comment by mobi-leuser** [comment] 2023-09-13 10:05
TTY

**Comment by mobi-leuser** [comment] 2023-09-13 11:16
Ah, good point! I'm pretty sure I was wearing it.

**Comment by elunna** [comment] 2023-09-13 11:26
I still cannot reproduce it even with the Mitre. I'll leave this issue up for a while longer in case someone else can, but I'll probably close it on the next release.

**Comment by elunna** [comment] 2023-09-14 12:13
It's possible this will be fixed in upcoming commit: 9a595ad87

**Closed** 2023-10-05 14:38 UTC
