### ISSUE TITLE
Weight of torch in sack changes

### ISSUE THREAD

**Issue by hothraxxa** [elunna/hackem#443] opened 2023-08-16 17:09 UTC
I have an identified sack. When I put a torcch (50 aum) into it, weight is reduced by 25 aum. I am a wizard so i know there's nothing magical about this torch. In case it matters, the torch has been used up.

**Comment by elunna** [comment] 2023-08-16 18:48
I wasn't able to reproduce this with a normal sack and a default torch yet.

Is it a default material torch (wood)?

Torches normally weigh 25, so is it by chance in a stack of 1 or more?

**Comment by hothraxxa** [comment] 2023-08-16 19:00
It is simply called an uncursed torch, no material specified. The shopkeeper who offers tool identification tells me that it's already identified. Putting it in a blessed bag of holding reduces my weight by 44!? Putting it in an (obviously empty) bag of rats is the same as putting it in a sack, i.e. weight is reduced by 25.

**Comment by elunna** [comment] 2023-08-16 20:20
What version are you playing?

**Comment by hothraxxa** [comment] 2023-08-16 20:26
That game is over. 1.2.0, current version on hardfought.

**Comment by hothraxxa** [comment] 2023-08-16 20:30
Just that torch. Didn't have another one to compare with.

**Comment by elunna** [comment] 2023-09-13 09:46
Closing this since I cannot reproduce it.

**Closed by elunna** 2023-09-13 09:46 UTC
